### ISSUE TITLE
Add "nostr" as topic

### ISSUE THREAD

**Issue by gourcetools** [thebrandonlucas/nostrlytics#2]
![image](https://user-images.githubusercontent.com/120996278/222979423-a9c975c1-a225-4535-83ba-4c8ea54b93ee.png)

**Comment by thebrandonlucas** [comment]
Good call! done.
<img width="329" alt="Screenshot 2023-03-06 at 9 45 59 AM" src="https://user-images.githubusercontent.com/38222767/223143638-ae5a9c4a-874b-4135-9880-4948b7751507.png">
